import turtle
def draw_art():
    window = turtle.Screen()
    window.bgcolor("yellow")

    brad = turtle.Turtle()
    brad.shape("turtle")
   # brad.color("red")
    brad.speed(2)
    brad.color("yellow")
    brad.right(90)
    brad.right(90)
    brad.forward(250)
    brad.right(90)
    brad.color("red")
    brad.forward(150)
    brad.right(90)
    brad.forward(80)
    brad.right(90)
    brad.color("yellow")
    brad.forward(70)
    brad.color("red")
    brad.right(90)
    brad.forward(80)
    brad.left(90)
    brad.forward(76)
    brad.left(90)
    brad.color("yellow")
    brad.forward(115)
    brad.color("red")
    brad.left(90)
    brad.forward(90)
    brad.right(90)
    brad.forward(65)
    brad.right(90)
    brad.forward(90)
    brad.right(90)
    brad.right(90)
    brad.forward(37)
    brad.left(90)
    brad.forward(65)
    brad.right(90)
    brad.right(90)
    brad.forward(65)
    brad.color("yellow")
    brad.forward(45)
    brad.color("red")
    brad.right(90)
    brad.forward(37)
    brad.right(90)
    brad.right(90)
    brad.forward(76)
    brad.color("yellow")
    brad.forward(15)
    brad.color("red")
    brad.right(90)
    brad.forward(8)
    brad.right(90)
    brad.forward(8)
    brad.right(90)
    brad.forward(8)
    brad.right(90)
    brad.forward(8)
    brad.right(90)
    brad.forward(8)
    brad.color("yellow")
    brad.forward(45)
    brad.color("red")
    brad.right(90)
    brad.forward(90)
    brad.right(90)
    brad.right(90)
    brad.forward(90)
    brad.right(90)
    brad.forward(40)
    brad.right(90)
    brad.forward(40)
    brad.right(90)
    brad.forward(40)
    brad.left(90)
    brad.left(45)
    brad.forward(80)
    brad.left(45)
    brad.color("yellow")
    brad.forward(40)
    brad.left(90)
    brad.forward(90)
    brad.color("red")
    brad.right(90)
    brad.forward(50)
    brad.right(90)
    brad.forward(90)
    brad.right(90)
    brad.forward(50)
    brad.right(90)
    brad.forward(90)
    brad.right(90)
    brad.forward(50)
    brad.color("yellow")
    brad.forward(37)
    brad.color("red")
    brad.forward(55)
    
    brad.right(135)
    #brad.right(45)
    brad.forward(100)
    brad.left(135)
    brad.forward(80)
    brad.color("yellow")
    brad.forward(30)
    brad.color("red")
    brad.right(145)
    brad.forward(100)
    brad.left(90)
    brad.color("yellow")
    brad.forward(15)
    brad.color("red")
    brad.left(90)    
    brad.forward(100)
    



    
    window.exitonclick()

draw_art()
